AdminSystem/urls.py
from .views import admin_view, book_view, account, user_view, order_view, author_view, press_view, logistics_view
from django.urls import path, include

urlpatterns = [
    path('', book_view.book_list),
    # 书籍的管理
    path('book/list/', book_view.book_list),
    path('book/add/', book_view.book_add),
    path('book/<int:nid>/edit/',book_view.book_edit),
    path('book/<int:nid>/delete/',book_view.book_delete),
    path('book/<int:nid>/details/',book_view.book_details),
    
    # # 作者的管理
    path('author/list/', author_view.author_list),
    path('author/add/', author_view.author_add),
    path('author/<int:nid>/edit/',author_view.author_edit),
    path('author/<int:nid>/delete/',author_view.author_delete),
    
    # 出版社的管理
    path('press/list/', press_view.press_list),
    path('press/add/', press_view.press_add),
    path('press/<int:nid>/edit/',press_view.press_edit),
    path('press/<int:nid>/delete/',press_view.press_delete),
    
    # 物流的管理
    path('logistics/list/', logistics_view.logistics_list),
    path('logistics/add/', logistics_view.logistics_add),
    path('logistics/<int:nid>/edit/',logistics_view.logistics_edit),
    path('logistics/<int:nid>/delete/',logistics_view.logistics_delete),
    
    # 订单的管理
    path('order/list/', order_view.order_list),
    path('order/<int:nid>/details/', order_view.order_details),
    path('order/<int:nid>/delete/', order_view.order_delete),
    path('order/<int:nid>/edit/', order_view.edit_order),

    path('orderlist/<int:nid>/delete/', order_view.order_list_delete),
    path('orderlist/<int:nid>/edit/', order_view.edit_order_list),

    # 评论的管理
    path('comment/<int:nid>/<int:book_id>/delete/',book_view.comment_delete),
    
    # 管理员的管理
    path('admin/list/', admin_view.admin_list),
    path('admin/add/', admin_view.admin_add),
    path('admin/<int:nid>/edit/', admin_view.admin_edit),
    path('admin/<int:nid>/delete/', admin_view.admin_delete),
    path('admin/<int:nid>/reset/', admin_view.admin_reset),

    # 用户的管理
    path('user/list/', user_view.user_list),
    path('user/add/', user_view.user_add),
    path('user/<int:nid>/edit/', user_view.user_edit),
    path('user/<int:nid>/delete/', user_view.user_delete),
    path('user/<int:nid>/reset/', user_view.user_reset),
    
    # 管理员登录
    path('login/', account.login),
    path('logout/', account.logout)
]

DSDouBan/urls.py
from django.contrib import admin
from django.urls import path, include
from UserSystem.views import account

urlpatterns = [
    path('admin/', admin.site.urls),
    # 管理员界面
    path('manager/', include('AdminSystem.urls')),
    path('dsdouban/', include('UserSystem.urls')),
    path('', account.home),
]

AdminSystem/models.py
from django.db import models


class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self):
        return self.username
    class Meta():
        verbose_name = '普通管理员' # 单数时显示内容
        verbose_name_plural = '普通管理员' # 复数时显示内容
    

class Book(models.Model):
    book_id = models.BigIntegerField(primary_key=True)
    title = models.CharField(max_length=45)
    publish_date = models.DateTimeField(blank=True, null=True)
    price_standard = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name="标准价格")      
    price_vip = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    score = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True, verbose_name="基础评分")
    score_current = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True, verbose_name="现行评分")
    edition = models.CharField(max_length=45, blank=True, null=True)
    storage = models.IntegerField(blank=True, null=True)
    class_field = models.ForeignKey('BookClass', models.DO_NOTHING, db_column='class_id', blank=True, null=False, default='8')  # Field renamed because it was a Python reserved word.
    press = models.ForeignKey('Press', models.DO_NOTHING, blank=True, null=True, verbose_name="出版社编号")
    introduction = models.CharField(max_length=2000, blank=True, null=True)
    authors = models.ManyToManyField('Author', through='BookAuthor')

    class Meta:
        managed = False
        db_table = 'book'
        indexes = [models.Index(fields=['title']),
                   models.Index(fields=['press']),
                   models.Index(fields=['introduction'])]


class BookClass(models.Model):
    class_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=45)
    parent_class = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_class'
        indexes = [models.Index(fields=['name']),]
        
    def __str__(self):
        return self.name


class Press(models.Model):
    press_id = models.BigAutoField(primary_key=True, verbose_name="出版社id")
    name = models.CharField(max_length=45)
    contact = models.CharField(max_length=45, blank=True, null=True)
    address = models.CharField(max_length=60, blank=True, null=True)
    tele = models.CharField(max_length=20, blank=True, null=True)
    email = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'press'
        indexes = [models.Index(fields=['name']),]
    
    def __str__(self):
        return self.name


class Author(models.Model):
    author_id = models.BigAutoField(primary_key=True)
    translator_choices = (
        (0, "作者"),
        (1, "译者"),
    )
    is_translator = models.IntegerField(default=0, choices=translator_choices)
    name = models.CharField(max_length=40)
    intro = models.CharField(max_length=800, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'author'
        indexes = [models.Index(fields=['name']),]
        
    def __str__(self):
        return self.name

class BookAuthor(models.Model):
    book = models.OneToOneField(Book, models.DO_NOTHING, primary_key=True)
    author = models.ForeignKey(Author, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'book_author'
        unique_together = (('book', 'author'),)
        indexes = [models.Index(fields=['book','author']),]


class Comments(models.Model):
    comment_id = models.BigIntegerField(primary_key=True)
    book = models.ForeignKey('Book', models.DO_NOTHING)
    user = models.ForeignKey('User', models.DO_NOTHING)
    submission_time = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=800)

    class Meta:
        managed = False
        db_table = 'comments'
        unique_together = (('book', 'user', 'submission_time'),)
        indexes = [models.Index(fields=['book','user']),]


class Logistics(models.Model):
    logistics_id = models.AutoField(primary_key=True)
    logistics_name = models.CharField(unique=True, max_length=30)
    logistics_tele = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'logistics'
    
    def __str__(self):
        return self.logistics_name


class Order(models.Model):
    order_id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey('User', models.DO_NOTHING)
    submission_time = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=20, default='未提交')
    """status 其他可选值为已付款,已完成和已取消"""
    logistics = models.ForeignKey(Logistics, models.DO_NOTHING, blank=True, null=True)
    telephone = models.CharField(max_length=15, blank=True, null=True)
    address = models.CharField(max_length=45, blank=True, null=True)
    name = models.CharField(max_length=40)
    vip_choices = (
        (0, "普通用户"),
        (1, 'VIP'),
    )
    is_vip = models.IntegerField(default=0, choices=vip_choices)

    class Meta:
        managed = False
        db_table = 'order'
        indexes = [models.Index(fields=['user','name']),]


class OrderList(models.Model):
    order_list_id = models.BigAutoField(primary_key=True)
    order = models.OneToOneField(Order, models.DO_NOTHING)
    book = models.ForeignKey(Book, models.DO_NOTHING)
    number = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'order_list'
        unique_together = (('order', 'book'),)


class User(models.Model):
    user_id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=10, verbose_name='用户名')
    password = models.CharField(max_length=40)
    vip_choices = (
        (0, "普通用户"),
        (1, "VIP"),
    )
    is_vip = models.IntegerField(default=0, choices=vip_choices, verbose_name='会员信息')
    telephone = models.CharField(max_length=15, blank=True, null=True)
    e_mail = models.CharField(max_length=45, blank=True, null=True)
    address = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'user'
        verbose_name = '普通用户' # 单数时显示内容
        verbose_name_plural = '普通用户' # 复数时显示内容
        indexes = [models.Index(fields=['name']),]

    def __str__(self):
        return self.name


class Mark(models.Model):
    mark_id = models.BigAutoField(primary_key=True)
    book = models.ForeignKey(Book, models.DO_NOTHING)
    user = models.ForeignKey(User, models.DO_NOTHING)
    marks = models.DecimalField(max_digits=3, decimal_places=1)

    class Meta:
        managed = False
        db_table = 'mark'
        unique_together = (('book', 'user'),)

# class AdminsystemAdmin(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     username = models.CharField(max_length=32)
#     password = models.CharField(max_length=64)

#     class Meta:
#         managed = False
#         db_table = 'adminsystem_admin'

# class AuthGroup(models.Model):
#     name = models.CharField(unique=True, max_length=150)

#     class Meta:
#         managed = False
#         db_table = 'auth_group'


# class AuthGroupPermissions(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
#     permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

#     class Meta:
#         managed = False
#         db_table = 'auth_group_permissions'
#         unique_together = (('group', 'permission'),)


# class AuthPermission(models.Model):
#     name = models.CharField(max_length=255)
#     content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
#     codename = models.CharField(max_length=100)

#     class Meta:
#         managed = False
#         db_table = 'auth_permission'
#         unique_together = (('content_type', 'codename'),)


# class AuthUser(models.Model):
#     password = models.CharField(max_length=128)
#     last_login = models.DateTimeField(blank=True, null=True)
#     is_superuser = models.IntegerField()
#     username = models.CharField(unique=True, max_length=150)
#     first_name = models.CharField(max_length=150)
#     last_name = models.CharField(max_length=150)
#     email = models.CharField(max_length=254)
#     is_staff = models.IntegerField()
#     is_active = models.IntegerField()
#     date_joined = models.DateTimeField()

#     class Meta:
#         managed = False
#         db_table = 'auth_user'


# class AuthUserGroups(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)
#     group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

#     class Meta:
#         managed = False
#         db_table = 'auth_user_groups'
#         unique_together = (('user', 'group'),)


# class AuthUserUserPermissions(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)
#     permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

#     class Meta:
#         managed = False
#         db_table = 'auth_user_user_permissions'
#         unique_together = (('user', 'permission'),)

# class DjangoAdminLog(models.Model):
#     action_time = models.DateTimeField()
#     object_id = models.TextField(blank=True, null=True)
#     object_repr = models.CharField(max_length=200)
#     action_flag = models.PositiveSmallIntegerField()
#     change_message = models.TextField()
#     content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)  
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)

#     class Meta:
#         managed = False
#         db_table = 'django_admin_log'


# class DjangoContentType(models.Model):
#     app_label = models.CharField(max_length=100)

AdminSystem/views/account.py
from io import BytesIO

from django import forms
from django.shortcuts import render, redirect, HttpResponse

from ..utils.code import check_code
from .. import models
from ..utils.bootstrap import BootStrapForm
from ..utils.encrypt import md5



class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(render_value=True),
        required=True
    )

    # code = forms.CharField(
    #     label="验证码",
    #     widget=forms.TextInput,
    #     required=True
    # )

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)


def login(request):
    """ 登录 """
    if request.method == "GET":
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证成功，获取到的用户名和密码
        # {'username': 'wupeiqi', 'password': '123',"code":123}
        # {'username': 'wupeiqi', 'password': '5e5c3bad7eb35cba3638e145c830c35f',"code":xxx}

        # # 验证码的校验
        # user_input_code = form.cleaned_data.pop('code')
        # code = request.session.get('image_code', "")
        # if code.upper() != user_input_code.upper():
        #     form.add_error("code", "验证码错误")
        #     return render(request, 'login.html', {'form': form})

        # 去数据库校验用户名和密码是否正确，获取用户对象、None
        # admin_object = models.Admin.objects.filter(username=xxx, password=xxx).first()
        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password", "用户名或密码错误")
            # form.add_error("username", "用户名或密码错误")
            return render(request, 'login.html', {'form': form})

        # 用户名和密码正确
        # 网站生成随机字符串; 写到用户浏览器的cookie中；在写入到session中；
        request.session["info"] = {'id': admin_object.id, 'name': admin_object.username, 'auth': "admin"}
        # session可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)

        return redirect("/manager/admin/list/")

    return render(request, 'login.html', {'form': form})


def image_code(request):
    """ 生成图片验证码 """

    # 调用pillow函数，生成图片
    img, code_string = check_code()

    # 写入到自己的session中（以便于后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给Session设置60s超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream, 'png')
    return HttpResponse(stream.getvalue())


def logout(request):
    """ 注销 """

    request.session.clear()

    return redirect('/dsdouban/login/')

AdminSystem/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">

        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                管理员信息列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>管理员名称</th>
                    <th>密码</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.id }}</th>
                        <th>{{ obj.username }}</th>
                        <td>****************</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

AdminSystem/templates/author_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">
            <a class="btn btn-success" href="/manager/author/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建作者
            </a>

            <div style="float: right;width: 500px;">
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search for..."
                               value="{{ search_data }}">

                        <span class="input-group-btn">
                        <button class="btn btn-default" type="submit">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                      </span>
                    </div>
                </form>
            </div>



        </div>

        {%if queryset%}
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                作者列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>id</th>
                    <th>姓名</th>
                    <th>译者/作者</th>
                    <th style="width: 750px;">简介</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <td>{{ obj.author_id }}</td>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.get_is_translator_display }}</td>
                        <td>{{ obj.intro }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/manager/author/{{obj.author_id}}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/manager/author/{{obj.author_id}}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>



        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>

        </div>


        {%else%}
            <h2>没有找到</h2>
        {%endif%}
    </div>
{% endblock %}

AdminSystem/templates/book_details.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">
            <a class="btn btn-primary" href="/manager/book/list/">
                <span aria-hidden="true"></span>
                返回
            </a>


        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>书名</th>
                    <th>出版日期</th>
                    <th>普通价格</th>
                    <th>会员价格</th>
                    <th>score</th>
                    <th>版本</th>
                    <th>出版社</th>
                    <th>类别</th>
                    <th>作者</th>
                </tr>
                </thead>
                <tbody>
                    <tr>
                    <th>{{ obj.title }}</th>
                    <td>{{ obj.publish_date|date:"Y-m-d" }}</td>
                    <td>{{ obj.price_standard }}</td>
                    <td>{{ obj.price_vip }}</td>
                    <td>{{ obj.score }}</td>
                    <td>{{ obj.edition }}</td>
                    <td>{{ obj.press }}</td>
                    <td>{{ obj.class_field }}</td>
                    <td>
                        {% for author in obj.authors.all %}
                            {{ author.name }};
                        {%endfor%}
                    </td>
                </tr>

                </tbody>
            </table>
            <h3>简介</h3>
            <h4>
                {{obj.introduction|linebreaksbr}}
            </h4>
            <h3>评论</h3>
            <h4>
            {% for cmt in comments %}
            <div>
                {{cmt.user.name}}:
                {{ cmt.comment }}
                <a class="btn btn-primary" href="/manager/comment/{{cmt.comment_id}}/{{cmt.book.book_id}}/delete/">
                    <span aria-hidden="true"></span>
                    删除评论
                </a>
            </div>
            {%endfor%}
            </h4>
        </div>

    </div>
{% endblock %}

AdminSystem/templates/book_list.html
{% extends 'layout.html' %}

{% block content %}

{% load get_key%}

    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">
            <a class="btn btn-success" href="/manager/book/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建书籍
            </a>

            <div style="float: right;width: 500px;">
                <form method="get">
                    <div class="input-group">
                        <div> 
                                
                        <input type="text" name="q" class="form-control" placeholder="Search for..."
                               value="{{ search_data }}" style="width: 140px;">
                        <input type="text" name="class_q" class="form-control" placeholder="搜索类别"
                               value="{{ search_class }}" style="width: 140px;">
                        <input type="text" name="parent_class_q" class="form-control" placeholder="搜索父类"
                        value="{{ search_parent_class }}" style="width: 140px;">

                               <button class="btn btn-default" type="submit">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </button>    
                        </div>
                    <div> 
                        <label for="orderby" style="font-family: ABeeZee, sans-serif;color: var(--bs-white);font-size: 15px;">Order by</label>
                        <select name="orderby" id="orderby" style="background:#fafdfe; height:28px; width:150px; line-height:28px; border:1px solid #9bc0dd; -moz-border-radius:2px; -webkit-border-radius:2px; border-radius:2px;">
                            <option value="{{ sort_option.name }}" style="display: none;" {% if not orderby %}selected=""{% endif %}>{{ sort_option.verbose_name }}</option>
                            <option value=""  style="display: none;"></option>
                            {% for field in sort_field %}
                            <option value="{{field.name}}" {% if field.name == orderby %}selected=""{% endif %}>{{field.verbose_name}}</option>
                            {% endfor %}
                        </select>

                        <label for="order" style="font-family: ABeeZee, sans-serif;color: var(--bs-white);font-size: 15px;">In</label>
                        <select name="order" id="order" style="background:#fafdfe; height:28px; width:150px; line-height:28px; border:1px solid #9bc0dd; -moz-border-radius:2px; -webkit-border-radius:2px; border-radius:2px;">
                            <option value="{{ sort_rule }}"  style="display: none;" {% if not order %}selected=""{% endif %}>{%if sort_rule == 'asc'%}从低到高{%else%}{%if sort_rule == 'desc'%}从高到低{%endif%}{%endif%}</option>
                            <option value=""  style="display: none;"></option>
                            <option value="asc" {% if order == "asc" %}selected=""{% endif %}>从低到高</option>
                            <option value="desc" {% if order == "desc" %}selected=""{% endif %}>从高到低</option>
                        </select>
                        <button class="btn btn-default" onclick=reset_sort() style="padding:4px 10px; border:1px solid #9bc0dd ;">
                                清空
                        </button>
                    </div> 
                      
                    </div>
                    
                
                
            </div>



        </div>
        {%if queryset%}
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                书籍信息列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>书名</th>
                    {% comment %} <th>出版日期</th> {% endcomment %}
                    <th>普通价格</th>
                    <th>会员价格</th>
                    <th>库存量</th>
                    <th>score</th>
                    {% comment %} <th>版本</th> {% endcomment %}
                    <th>出版社</th>
                    <th style="width: 60px;">类别</th>
                    <th style="width: 500px;">简介</th>
                    <th>作者</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.title }}</th>
                        {% comment %} <td>{{ obj.publish_date|date:"Y-m-d" }}</td> {% endcomment %}
                        <td>{{ obj.price_standard }}</td>
                        <td>{{ obj.price_vip }}</td>
                        <td>{{ obj.storage }}</td>
                        <td>{{ obj.score }}</td>
                        {% comment %} <td>{{ obj.edition }}</td> {% endcomment %}
                        <td>{{ obj.press }}</td>
                        <td>{{ obj.class_field }}</td>
                        <td>{{ extract|get_dictionary_item:obj.book_id}}</td>
                        <td>
                            {% for author in obj.authors.all %}
                                {{ author.name }};
                            {%endfor%}
                        </td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/manager/book/{{obj.book_id}}/edit/">编辑</a>
                            <a class="btn btn-primary btn-xs" href="/manager/book/{{obj.book_id}}/details/">查看详情</a>
                            <a class="btn btn-danger btn-xs" href="/manager/book/{{obj.book_id}}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <div class="clearfix">
            <ul class="pagination">
                {{ page_string }}
            </ul>

        </div>

        {%else%}
            <h2>没有找到</h2>
        {%endif%}
    </div>

</form>
    <script type="text/javascript">
        function reset_sort()
        {
            document.getElementById("orderby").options[1].selected=true;
            document.getElementById("order").options[1].selected=true;
        }
    </script>
{% endblock %}

AdminSystem/templates/change.html
{% extends 'layout.html' %}


{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> {{ title }} </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}

                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

AdminSystem/templates/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/manager/user/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户
            </a>

        </div>
        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                用户信息列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>用户名称</th>
                    <th>密码</th>
                    <th>是否VIP</th>
                    <th>电话</th>
                    <th>邮箱地址</th>
                    <th>地址</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th>{{ obj.user_id }}</th>
                        <th>{{ obj.name }}</th>
                        <td>*******</td>
                        <td>{{ obj.get_is_vip_display  }}</td>
                        <td>{{ obj.telephone  }}</td>
                        <td>{{ obj.e_mail  }}</td>
                        <td>{{ obj.address  }}</td>

                        <td>
                            <a href="/manager/user/{{ obj.user_id }}/reset/">重置密码</a>
                        </td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/manager/user/{{obj.user_id}}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/manager/user/{{obj.user_id}}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}