DSDouBan/urls.py
from django.contrib import admin
from django.urls import path, include
from UserSystem.views import account

urlpatterns = [
    path('admin/', admin.site.urls),
    # 管理员界面
    path('manager/', include('AdminSystem.urls')),
    path('dsdouban/', include('UserSystem.urls')),
    path('', account.home),
]

UserSystem/urls.py
from .views import account, book_view, user_order, other_view
from django.urls import path, include

urlpatterns = [
    # 用户登录与注册
    path('', account.begin),
    path('register/', account.register),
    path('login/', account.login),
    path('logout/', account.logout),
    path('user_details/', account.user_details),
    path('edit_user_details/', account.edit_user_details),
    path('reset_user_pwd/', account.reset_user_password),
    
    # 图书的查看
    # 这里nid是book_id
    path('book/list/', book_view.book_list),
    path('book/<int:nid>/details/',book_view.book_details),
    path('book/<int:nid>/add_book_to_unsubmitted_order_list/',user_order.add_book_to_unsubmitted_order_list),
    
    # 订单的管理
    # 这里nid是user_id
    path('order/unsubmitted_order/', user_order.show_unsubmitted_order),
    path('order/submitted_orders/', user_order.show_submitted_orders),
    path('order/submit_unsubmitted_order/', user_order.submit_unsubmitted_order),
    path('order/<int:nid>/edit_unsubmitted_order/', user_order.edit_unsubmitted_order),
    
    #这里nid是order_id
    path('order/<int:nid>/detail_order/', user_order.show_submitted_order_details),
    path('order/<int:nid>/edit_order/', user_order.edit_submitted_order),
    path('order/<int:nid>/finish_order/', user_order.finish_submitted_order),
    path('order/<int:nid>/cancel_order/', user_order.cancel_submitted_order),


    # 这里nid是order_list_id
    path('order/<int:nid>/edit_unsubmitted_order_list/', user_order.edit_unsubmitted_order_list),
    path('order/<int:nid>/delete_unsubmitted_order_list/', user_order.delete_unsubmitted_order_list),
    
    # Comments
    path('comments/<int:nid>/delete/', book_view.comment_delete),
    path('comments/<int:nid>/update/', book_view.comment_update),

    #这里nid是author_id
    path('author/<int:nid>/',other_view.author_view),

    #这里nid是press_id
    path('press/<int:nid>/',other_view.press_view),

    path('upgrade/',account.upgrade),
]

AdminSystem/models.py
from django.db import models


class Admin(models.Model):
    """ 管理员 """
    username = models.CharField(verbose_name="用户名", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=64)

    def __str__(self):
        return self.username
    class Meta():
        verbose_name = '普通管理员' # 单数时显示内容
        verbose_name_plural = '普通管理员' # 复数时显示内容
    

class Book(models.Model):
    book_id = models.BigIntegerField(primary_key=True)
    title = models.CharField(max_length=45)
    publish_date = models.DateTimeField(blank=True, null=True)
    price_standard = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name="标准价格")      
    price_vip = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    score = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True, verbose_name="基础评分")
    score_current = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True, verbose_name="现行评分")
    edition = models.CharField(max_length=45, blank=True, null=True)
    storage = models.IntegerField(blank=True, null=True)
    class_field = models.ForeignKey('BookClass', models.DO_NOTHING, db_column='class_id', blank=True, null=False, default='8')  # Field renamed because it was a Python reserved word.
    press = models.ForeignKey('Press', models.DO_NOTHING, blank=True, null=True, verbose_name="出版社编号")
    introduction = models.CharField(max_length=2000, blank=True, null=True)
    authors = models.ManyToManyField('Author', through='BookAuthor')

    class Meta:
        managed = False
        db_table = 'book'
        indexes = [models.Index(fields=['title']),
                   models.Index(fields=['press']),
                   models.Index(fields=['introduction'])]


class BookClass(models.Model):
    class_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=45)
    parent_class = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'book_class'
        indexes = [models.Index(fields=['name']),]
        
    def __str__(self):
        return self.name


class Press(models.Model):
    press_id = models.BigAutoField(primary_key=True, verbose_name="出版社id")
    name = models.CharField(max_length=45)
    contact = models.CharField(max_length=45, blank=True, null=True)
    address = models.CharField(max_length=60, blank=True, null=True)
    tele = models.CharField(max_length=20, blank=True, null=True)
    email = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'press'
        indexes = [models.Index(fields=['name']),]
    
    def __str__(self):
        return self.name


class Author(models.Model):
    author_id = models.BigAutoField(primary_key=True)
    translator_choices = (
        (0, "作者"),
        (1, "译者"),
    )
    is_translator = models.IntegerField(default=0, choices=translator_choices)
    name = models.CharField(max_length=40)
    intro = models.CharField(max_length=800, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'author'
        indexes = [models.Index(fields=['name']),]
        
    def __str__(self):
        return self.name

class BookAuthor(models.Model):
    book = models.OneToOneField(Book, models.DO_NOTHING, primary_key=True)
    author = models.ForeignKey(Author, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'book_author'
        unique_together = (('book', 'author'),)
        indexes = [models.Index(fields=['book','author']),]


class Comments(models.Model):
    comment_id = models.BigIntegerField(primary_key=True)
    book = models.ForeignKey('Book', models.DO_NOTHING)
    user = models.ForeignKey('User', models.DO_NOTHING)
    submission_time = models.DateTimeField(auto_now=True)
    comment = models.CharField(max_length=800)

    class Meta:
        managed = False
        db_table = 'comments'
        unique_together = (('book', 'user', 'submission_time'),)
        indexes = [models.Index(fields=['book','user']),]


class Logistics(models.Model):
    logistics_id = models.AutoField(primary_key=True)
    logistics_name = models.CharField(unique=True, max_length=30)
    logistics_tele = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'logistics'
    
    def __str__(self):
        return self.logistics_name


class Order(models.Model):
    order_id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey('User', models.DO_NOTHING)
    submission_time = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=20, default='未提交')
    """status 其他可选值为已付款,已完成和已取消"""
    logistics = models.ForeignKey(Logistics, models.DO_NOTHING, blank=True, null=True)
    telephone = models.CharField(max_length=15, blank=True, null=True)
    address = models.CharField(max_length=45, blank=True, null=True)
    name = models.CharField(max_length=40)
    vip_choices = (
        (0, "普通用户"),
        (1, 'VIP'),
    )
    is_vip = models.IntegerField(default=0, choices=vip_choices)

    class Meta:
        managed = False
        db_table = 'order'
        indexes = [models.Index(fields=['user','name']),]


class OrderList(models.Model):
    order_list_id = models.BigAutoField(primary_key=True)
    order = models.OneToOneField(Order, models.DO_NOTHING)
    book = models.ForeignKey(Book, models.DO_NOTHING)
    number = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'order_list'
        unique_together = (('order', 'book'),)


class User(models.Model):
    user_id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=10, verbose_name='用户名')
    password = models.CharField(max_length=40)
    vip_choices = (
        (0, "普通用户"),
        (1, "VIP"),
    )
    is_vip = models.IntegerField(default=0, choices=vip_choices, verbose_name='会员信息')
    telephone = models.CharField(max_length=15, blank=True, null=True)
    e_mail = models.CharField(max_length=45, blank=True, null=True)
    address = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'user'
        verbose_name = '普通用户' # 单数时显示内容
        verbose_name_plural = '普通用户' # 复数时显示内容
        indexes = [models.Index(fields=['name']),]

    def __str__(self):
        return self.name


class Mark(models.Model):
    mark_id = models.BigAutoField(primary_key=True)
    book = models.ForeignKey(Book, models.DO_NOTHING)
    user = models.ForeignKey(User, models.DO_NOTHING)
    marks = models.DecimalField(max_digits=3, decimal_places=1)

    class Meta:
        managed = False
        db_table = 'mark'
        unique_together = (('book', 'user'),)

# class AdminsystemAdmin(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     username = models.CharField(max_length=32)
#     password = models.CharField(max_length=64)

#     class Meta:
#         managed = False
#         db_table = 'adminsystem_admin'

# class AuthGroup(models.Model):
#     name = models.CharField(unique=True, max_length=150)

#     class Meta:
#         managed = False
#         db_table = 'auth_group'


# class AuthGroupPermissions(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
#     permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

#     class Meta:
#         managed = False
#         db_table = 'auth_group_permissions'
#         unique_together = (('group', 'permission'),)


# class AuthPermission(models.Model):
#     name = models.CharField(max_length=255)
#     content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
#     codename = models.CharField(max_length=100)

#     class Meta:
#         managed = False
#         db_table = 'auth_permission'
#         unique_together = (('content_type', 'codename'),)


# class AuthUser(models.Model):
#     password = models.CharField(max_length=128)
#     last_login = models.DateTimeField(blank=True, null=True)
#     is_superuser = models.IntegerField()
#     username = models.CharField(unique=True, max_length=150)
#     first_name = models.CharField(max_length=150)
#     last_name = models.CharField(max_length=150)
#     email = models.CharField(max_length=254)
#     is_staff = models.IntegerField()
#     is_active = models.IntegerField()
#     date_joined = models.DateTimeField()

#     class Meta:
#         managed = False
#         db_table = 'auth_user'


# class AuthUserGroups(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)
#     group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

#     class Meta:
#         managed = False
#         db_table = 'auth_user_groups'
#         unique_together = (('user', 'group'),)


# class AuthUserUserPermissions(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)
#     permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

#     class Meta:
#         managed = False
#         db_table = 'auth_user_user_permissions'
#         unique_together = (('user', 'permission'),)

# class DjangoAdminLog(models.Model):
#     action_time = models.DateTimeField()
#     object_id = models.TextField(blank=True, null=True)
#     object_repr = models.CharField(max_length=200)
#     action_flag = models.PositiveSmallIntegerField()
#     change_message = models.TextField()
#     content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)  
#     user = models.ForeignKey(AuthUser, models.DO_NOTHING)

#     class Meta:
#         managed = False
#         db_table = 'django_admin_log'


# class DjangoContentType(models.Model):
#     app_label = models.CharField(max_length=100)

UserSystem/models.py
from django.db import models

# Create your models here.

UserSystem/views/other_view.py
import copy
from django import forms
from django.utils import timezone
from django.shortcuts import render, redirect
from AdminSystem.utils.pagination import Pagination

from AdminSystem import models






def author_view(request, nid):
    author_obj = models.Author.objects.filter(author_id=nid).first()
    content = { 'obj':author_obj,
    }
    return render(request, 'user_author_detail.html', content)


def press_view(request, nid):
    press_obj = models.Press.objects.filter(press_id=nid).first()
    content = { 'obj':press_obj,
    }
    return render(request, 'user_press_detail.html', content)

UserSystem/templates/comment_update.html
{% load static %}
{% load get_key %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{page_title}}</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
        * {
            margin: 0;
            padding: 0;
            -webkit-font-smoothing: antialiased;
            -webkit-text-shadow: rgba(0, 0, 0, .01) 0 0 1px;
            text-shadow: rgba(0, 0, 0, .01) 0 0 1px
        }

        body {
            font-family: 'Rubik', sans-serif;
            font-size: 14px;
            font-weight: 400;
            background: beige;
            color: #000000
        }

    </style>
</head>
<body>





{% include "head_nav.html"%}   

    <div class="container" style="margin-top: 100px; width: 500px;">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> {{ title }} </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                            <div class="form-group">
                                <label>评论</label>                        
                                <textarea type="text" name="comment" style="min-height: 200px;" class="form-control" placeholder="发表你的感想吧" required="" id="id_comment">{{comment_content}}</textarea>
                                <span style="color: red;">{{ field.errors.0 }}</span>
                            </div>
                    {% endfor %}
                    <div style=" width:58px;margin:auto; margin-top: 20px;">
                        <button type="submit" class="btn btn-primary" >提 交</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
    
    </body>
    </html>

UserSystem/templates/head_sub.html
{% load static %}
<div class='subhead' style="height: 125px; 
background-color: #FFEECE;
margin-top: 25px;
margin-bottom: 10px;">
        <div class="col-xs-2 col-md-offset-1">
            <div>
                <img src="{% static "img\logo2.png" %}"
                data-holder-rendered="true" style="width: 250px; margin-top: 15px; margin-bottom: 15px;">
            </div>
        </div>

        <div class="col-xs-6 ">
            <div style="margin-bottom: 10px; margin-top: 20px; margin-left: 20px;" >
                <div style="width: 450px;">
                    <form method="get" action="/">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="书名、作者、简介、ISBN"
                                   value="{{ search_data }}">
                            <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div style="height:1px; width:100%; background:#251E0F; overflow:hidden;"></div>


        <div class="col-xs-2 col-md-offset--1">

        </div>
</div>

UserSystem/templates/register_success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册成功</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .info{
            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class=info>
        <h1>  注册成功！正在跳转..</h1>
    </div>

    <script type="text/javascript">
        setInterval(returnLogin, 1500);
        function returnLogin()
        {
            window.location.href='/dsdouban/login/'
        }
    </script>
</body>
</html>

UserSystem/templates/unsub_order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>豆丝豆瓣·购物车</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
        * {
            margin: 0;
            padding: 0;
            -webkit-font-smoothing: antialiased;
            -webkit-text-shadow: rgba(0, 0, 0, .01) 0 0 1px;
            text-shadow: rgba(0, 0, 0, .01) 0 0 1px
        }

        body {
            font-family: 'Rubik', sans-serif;
            font-size: 14px;
            font-weight: 400;
            background: beige;
            color: #000000
        }

        
    </style>
</head>
<body>





{% include "head_nav.html"%}    


<div class="container">
<div class="cart_section">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-10 offset-lg-1">
                    <div class="cart_container">

                        <div class="cart_items">
                            <ul class="cart_list">
                            <li class="cart_item clearfix">
                                    <div class="cart_item_info d-flex flex-md-row flex-column justify-content-between" style="width:calc(100%)">
                                        <div style="float: left;">
                                            <div style="margin-left: 7.53%;">
                                                <div class="cart_item_text" style="width: 300px;font-size:40px;">{{ order.user }}</div>
                                            </div>
                                            <div style="margin-left: 7.53%;margin-top: 30px;color: rgba(0, 0, 0, 0.5);">
                                                {{order.user.get_is_vip_display}}
                                            </div>
                                        </div>
                                        <div style="float: right; margin-right: 0;">
                                            <div class="cart_item_number cart_info_col">
                                                <div class="cart_item_title">收件人</div>
                                                <div class="cart_item_text">{{ order.name }}</div>
                                            </div>
                                            <div class="cart_item_number cart_info_col">
                                                <div class="cart_item_title">收件人电话</div>
                                                <div class="cart_item_text">{{ order.telephone }}</div>
                                            </div>
                                            <div class="cart_item_number cart_info_col">
                                                <div class="cart_item_title">地址</div>
                                                <div class="cart_item_text">{{ order.address }}</div>
                                            </div>
                                            <div class="cart_item_number cart_info_col">
                                                    <div class="cart_item_title">物流方式</div>
                                                    <div class="cart_item_text">{{ order.logistics }}</div>
                                                </div>
                                                
                                                
                                            <div class="cart_item_number cart_info_col">
                                                    <a href = '/dsdouban/order/{{order.order_id}}/edit_unsubmitted_order/'>
                                                        <div class="cart_item_title">
                                                            <div class="cart_item_title" style="margin-left: 7.53%;min-width:80px;">[修改信息]</div>
                                                        </div>
                                                        </a>
                                            </div>
                                                
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>



                        <div class="cart_title">购物车</div>
                        <div class="cart_items">
                            <ul class="cart_list">


                                



                               




                                {% for book_order in order_list %}

                                <li class="cart_item clearfix">
                                    <div class="cart_item_image"><img src="\static\img_book\{{book_order.book_id}}.jpg" alt="">
                                    </div>
                                    <div class="cart_item_info d-flex flex-md-row flex-column justify-content-between">
                                        <div style="float: left;">
                                            <div style="margin-left: 7.53%;">
                                                <div class="cart_item_text" style="width: 300px;">{{book_order.book.title}}</div>
                                            </div>
                                            <a href = '\dsdouban\book\{{book_order.book_id}}\details\'>
                                            <div class="cart_item_color cart_info_col">
                                                <div class="cart_item_title" style="margin-left: 7.53%;">[详细信息]</div>
                                            </div>
                                            </a>
                                        </div>
                                        <div style="float: right;" class='money_part'>
                                            <div class="cart_item_number cart_info_col">
                                                <div class="cart_item_title">数量</div>
                                                <div class="cart_item_text">{{ book_order.number }}</div>
                                            </div>
                                            <div class="cart_item_price cart_info_col">
                                                {% if order.user.is_vip == 0 %}
                                                <div class="cart_item_title">单价</div>
                                                <div class="cart_item_text">{{ book_order.book.price_standard }}</div>
                                                {%else%}
                                                <div class="cart_item_title">会员价</div>
                                                <div class="cart_item_text">{{ book_order.book.price_vip }}</div>
                                                {%endif%}
                                            </div>
                                            <div class="cart_item_number cart_info_col" style="margin-bottom: 0px;">
                                                    <a href = '/dsdouban/order/{{book_order.order_list_id}}/edit_unsubmitted_order_list/'>
                                                        <div class="cart_item_title">
                                                            <div class="cart_item_title" style="margin-left: 7.53%;min-width:80px;">[修改数量]</div>
                                                        </div>
                                                        </a>
                                            </div>
                                            <div class="cart_item_number cart_info_col" >
                                                    <a href = '/dsdouban/order/{{book_order.order_list_id}}/delete_unsubmitted_order_list/'>
                                                        <div class="cart_item_title" style="margin-top: 0px;">
                                                            <div class="cart_item_title" style="margin-left: 7.53%;min-width:50px;margin-top: 5px;">[删除]</div>
                                                        </div>
                                                        </a>
                                            </div>
                                        </div>
                                    </div>
                                </li>


                                {%endfor%}

                            </ul>
                        </div>
                        <div class="order_total">
                            <div class="order_total_content text-md-right">
                                <div class="order_total_title">订单总额：</div>
                                <div class="order_total_amount" id='Total'>0</div>
                            </div>
                        </div>

                        
                                {%if warning_info%}
                            <h4 style="color: red;">
                                {{warning_info}}
                            </h4>
                                {%endif%}
                            
                        <div class="cart_buttons"> 

                                <a  href="/">
                                <button type="button" class="button cart_button_clear">返回首页</button>
                                </a>
                                <a  href="/dsdouban/order/submit_unsubmitted_order/">
                                <button type="button" class="button cart_button_checkout">提交订单</button> 
                                </a>
                            </div>
                                </div>



                </div>
            </div>
        </div>
    </div>
</div>







<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
<script type="text/javascript">
    function calculate_total(){
        var elements = document.getElementsByClassName("money_part");
        var money_total = 0;
        for(var i = 0; i < elements.length; i++){
            var num = elements[i].getElementsByClassName('cart_item_number');
            num = num[0].getElementsByClassName('cart_item_text');
            num = parseInt(num[0].textContent);
            var price = elements[i].getElementsByClassName('cart_item_price');
            price = price[0].getElementsByClassName('cart_item_text');
            price = parseFloat(price[0].textContent);
            money_total+=price*num;
        }
        document.getElementById("Total").textContent = money_total.toFixed(2);
    }

    calculate_total();
</script>

</body>
</html>

UserSystem/templates/unsub_order_change.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>豆丝豆瓣·购物车</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
        * {
            margin: 0;
            padding: 0;
            -webkit-font-smoothing: antialiased;
            -webkit-text-shadow: rgba(0, 0, 0, .01) 0 0 1px;
            text-shadow: rgba(0, 0, 0, .01) 0 0 1px
        }

        body {
            font-family: 'Rubik', sans-serif;
            font-size: 14px;
            font-weight: 400;
            background: beige;
            color: #000000
        }

    </style>
</head>
<body>





{% include "head_nav.html"%}   

    <div class="container" style="margin-top: 100px; width: 400px;">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> {{ title }} </h3>
            </div>
            <div class="panel-body">
                <form method="post" novalidate>
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group" style="width: 200px; margin: auto;">
                            <label style="margin-top: 10px;">
                                {%if field.label == 'Logistics'%}
                                物流方式
                                {%else%}
                                    {%if field.label == 'Telephone'%}
                                    收件人电话
                                    {%else%}
                                        {%if field.label == 'Address'%}
                                        收件人地址
                                        {%else%}
                                            {%if field.label == 'Name'%}
                                            收件人姓名
                                            {%endif%}
                                        {%endif%}
                                    {%endif%}
                                {%endif%}
                                </label>
                            {{ field }}
                            <span style="color: red;">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <div style=" width:100px;margin:auto; margin-top: 20px;">
                        <button type="submit" class="btn btn-primary" >提 交</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
    
    </body>
    </html>